#!/bin/sh
#Configurations injected by install_server below....

EXEC=/usr/local/bin/redis-server
{% if config.get('requirepass') %}
CLIEXEC="/usr/local/bin/redis-cli -a {{ config.get('requirepass') }}"
{% else %}
CLIEXEC=/usr/local/bin/redis-cli
{% endif %}
PIDFILE=/var/run/redis_{{ config.get('port') }}.pid
CONF="/etc/redis/{{ config.get('port') }}.conf"
REDISPORT="{{ config.get('port') }}"
###############
# SysV Init Information
# chkconfig: - 58 74
# description: redis_{{ config.get('port') }} is the redis daemon.
### BEGIN INIT INFO
# Provides: redis_{{ config.get('port') }}
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Should-Start: $syslog $named
# Should-Stop: $syslog $named
# Short-Description: start and stop redis_{{ config.get('port') }}
# Description: Redis daemon
### END INIT INFO


case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting Redis server..."
            $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping ..."
            $CLIEXEC -p $REDISPORT shutdown
            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis to shutdown ..."
                sleep 1
            done
            echo "Redis stopped"
        fi
        ;;
    status)
        if [ ! -f $PIDFILE ]
        then
            echo 'Redis is not running'
        else
            echo "Redis is running ($(<$PIDFILE))"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac